Add-WindowsFeature web-server
Add-WindowsFeature web-common-http -IncludeAllSubFeature
Add-WindowsFeature Web-Health -IncludeAllSubFeature
Add-WindowsFeature Web-Performance -IncludeAllSubFeature
Add-WindowsFeature Web-Security -IncludeAllSubFeature
Add-WindowsFeature Web-Metabase
Add-WindowsFeature Web-Net-Ext
Add-WindowsFeature Web-Net-Ext45
Add-WindowsFeature Web-ISAPI-Ext
Add-WindowsFeature Web-ISAPI-Filter
Add-WindowsFeature Web-Asp-Net
Add-WindowsFeature Web-Asp-Net45
Add-WindowsFeature NET-Framework-Features
Add-WindowsFeature NET-Framework-45-Features
Add-WindowsFeature Web-Mgmt-Console
